- README.md
- src/localize.js
- src/translations/fr.json
> French translation

- README.md
- src/localize.js
- src/translations/et.json
> Estonian translation

- README.md
- src/localize.js
- src/translations/nl.json
> Dutch translation

- README.md
- src/localize.js
- src/translations/de.json
I've added a German translation, nothing spectacular.
> Add German translation

- src/translations/nl.json
> Tweak Dutch

- README.md
- src/localize.js
- src/translations/es.json
I added spanish translations to localization folder.
Keep doing such a great work!
> Add spanish translation

- src/translations/nl.json
> Add missing strings to Dutch translation

- src/data.js
- src/integrations/meteofrance-integration.js
- src/translations/fr.json
Hi 😃 
Today my card stoped working for the good reason méteo france started return new event.
So this is the fix
> Fix Météo France intégration + Update French translation

- src/translations/de.json
This PR enhances the german translation and adds some missing translations.
> Improve german translation

- src/integrations/meteofrance.js
Hello :)
Météo France started to expose a new key for the event "Extreme low temperature", so i made the modification :)
> Add "Extreme low temperature" event for MétéoFrance integration

- src/editor.js
- src/meteoalarm-card.js
- src/translations/de.json
- src/translations/en.json
- src/translations/es.json
- src/translations/et.json
- src/translations/fr.json
- src/translations/it.json
- src/translations/nl.json
- src/translations/pl.json
- src/translations/schema/schema.json
- src/translations/sv.json
Fixes: #54
This is a very sketchy solution, but it works 🎉
> Hide card when there are no warnings

- src/translations/et.json
Best and thanks for nice new features :-)
JR
> Update Estonian translation

- README.md
- src/localize.js
- src/translations/hr.json
Hi,
I added Croatian translation
> Add Croatian translation

- src/integrations/weatheralerts.js
I really like the idea of the card and live in Coastal Florida.  I did add two alerts that we currently have that are not allowing the card to be shown.  Please advise if I have done so incorrectly.  I am not new to developing but have not done much in Java.
> Add missing weatheralerts events

- src/meteoalarm-card.ts
> Fix `hide_when_no_warning`

- src/localize/languages/sk.json
supplementing the descriptions of version 2.0
> Update Slovak translation

- src/localize/languages/hr.json
> Update Croatian translation

- README.md
- src/localize/languages/pt.json
- src/localize/localize.ts
Translation for Portuguese (Portugal) - .pt
> Add Portuguese Translation

- src/integrations/meteoalarm.ts
- src/meteoalarm-card.ts
- src/types.ts
> Fix font color on light theme

- src/localize/languages/it.json
Missing strings (null) were added and incorrect strings were corrected (syntactically and orthographically)
> Update Italian Translation

- src/integrations/dwd.ts
Fixes: #119
Fix dwd level 4 to be converted into level 3 on meteoalarm scale
> Fix DWD alerts with level 4

- src/integrations/env_canada.ts
Fixes #100
This still needs testing for watches
> French support for env canada

- dosc/scaling-mode.md
- src/editor.ts
- src/localize/languages/bg.json
- src/localize/languages/cs.json
- src/localize/languages/de.json
- src/localize/languages/en.json
- src/localize/languages/es.json
- src/localize/languages/et.json
- src/localize/languages/fr.json
- src/localize/languages/hr.json
- src/localize/languages/it.json
- src/localize/languages/nl.json
- src/localize/languages/pl.json
- src/localize/languages/pt.json
- src/localize/languages/sk.json
- src/localize/languages/sv.json
- src/localize/schema/schema.json
- src/measure-text.ts
- src/meteoalarm-card.ts
- src/styles.ts
- src/types.ts
> Rework card scaling system

- src/integrations/env_canada.ts
> Fix Environment Canada warning for French "Froid Extrême" (Extreme Cold)

- src/integrations/weatheralerts.ts
> Use actual event name as warnings title in weatheralerts

- src/integrations/weatheralerts.ts
> Add `Rip Current` event to weatheralerts

- src/integrations/weatheralerts.ts
> Add Blowing Dust even type to Weatheralerts

- src/integrations/dwd.ts
Adds DWD event id `248` as raised in issue <https://github.com/MrBartusek/MeteoalarmCard/issues/208>
> Add support for event id `248` to DWD integration

- .eslintrc.cjs
- package-lock.json
- package.json
- src/data.ts
- src/editor-warnings.ts
- src/editor.ts
- src/events-praser.ts
- src/external/swiperStyles.ts
- src/helpers/action-handler-directive.ts
- src/helpers/process-config-entities.ts
- src/helpers/process-editor-entities.ts
- src/integrations/burze_dzis_net.ts
- src/integrations/dwd.ts
- src/integrations/env_canada.ts
- src/integrations/integrations.ts
- src/integrations/meteoalarm.ts
- src/integrations/meteofrance.ts
- src/integrations/nina.ts
- src/integrations/weatheralerts.ts
- src/localize/localize.ts
- src/measure-text.ts
- src/meteoalarm-card.ts
- src/predefined-cards.ts
- src/styles.ts
- src/types.ts
- src/utils.ts
- yarn.lock
> Update eslint rules & update eslint-related dependencies

- README.md
- src/localize/languages/fi.json
- src/localize/localize.ts
Here is my contribution to this card. Thanks for the great card!
I translated src/localize/languages/en.json file and named it to fi.json.
Imported my translation in src/localize/localize.ts file.
And mentioned my translation in README.md file.
Hope this Pull Request is done the right way.
> Add Finnish language

- src/localize/languages/es.json
add few missing translations to Spanish localization
> Update Spanish translation
