MrBartusek/MeteoalarmCard

src/translations/fr.json
This PR fixes spelling errors and adds missing translations to the French translation.
=> Update French translation

src/integrations/meteofrance.js, src/translations/fr.json
Hey :)
I finally take a look into the source code to find the complete list of event, instead find them one by one ...
I don't know why I didn't do that directly
Also, I found some invisible char into translation, I replace them by space like other translation.
Fixes: #74
=> Add missing events to MeteoFrance & update French translation

src/data.ts, src/util.ts
Fixes: #91
This replaces the old `weather-windy` icon with a new `weather-dust` when version 2022.08 or higher is detected.
=> Update Dust event icon to `weather-dust`  (HA 2022.08)

src/meteoalarm-card.ts
2.0.0 introduced a bug where stub config won't be generated using `entities` and still uses pre-2.0 config. This PR fixes this bug. I've also gone ahead and excluded multiple entity integrations from the stub config.
=> Fix default (stub) configuration

src/meteoalarm-card.ts
Fixes: #157
Card sizes were incorrectly measured on very small sizes, this now works well:
=> Fix card scaling on very small sizes

src/integrations/nina.ts, src/utils.ts
Fix: #163
Some integrations can use different names for different severities. For example, the `Moderate` severity is yellow in every other integration but, NINA uses it for orange alerts. For that reason, `getLevelBySeverity` now has the ability to accept `overrides` which NINA use for this severity.
=> Add `overrides` to getLevelBySeverity (fix NINA severities)

src/utils.ts
MeteoalarmCard uses the frontend version for disabling and enabling some features on the fly. For example we tend to use newly added icons for some alerts. The dust warning alerts show `mdi:weather-dust` icon only in HA 2022.08 and newer. For older version we show `mdi:weather-windy`
This check was broken since version 2023.01 and has caused some alerts to show old icons and printed invalid warnings to the console. This PR fixes this check.
(this is 2023.3.6)
=> Fix HA frotnent version check

src/meteoalarm-card.ts, src/types.ts
When the user provides an arbitrary `entity_id` or provided entity no longer exists it spits out an error card. This fixes it so it will show a nice entity unavailable card.
=> Fix integration unavailable card

src/editor.ts, src/integrations/env_canada.ts, src/types.ts
Fixes: #127
Add support for the fourth entity provided by Environment Canada, advisories are now shown as yellow alerts. This probably needs some information in the release so users can add their entity.
=> Enviroment Canada advisory alerts support

.vscode/settings.json, src/integrations/weatheralerts.ts
Fixes:  #167 - Adds Freeze event
Fixes: #145 - Rewrite event severity detection
This PR is a rewrite of event detection in weatheralerts integration. It should now properly detect event severities from event names and detect events that were otherwise missing.
=> Rewrite weatheralerts integration

src/meteoalarm-card.ts, src/predefined-cards.ts
=> Fix `hide_when_no_warning`

src/integrations/weatheralerts.ts
Fix: #185
Add missing event types to weatheralerts 
- Special Weather
- High Surf
- Hazardous Seas
- Beach Hazard
Also, support the `Statements` as orange level
=> Add missing weatheralerts event types

src/integrations/weatheralerts.ts, src/utils.ts
Fixes: #195
Sample Warning from NWS...
https://forecast.weather.gov/wwamap/wwatxtget.php?cwa=usa&wwa=Special%20Weather%20Statement
For some reason it is not listed on the nws definition page for alerts, https://www.weather.gov/lwx/WarningsDefined
I think this solution can be boiled down to being a thunderstorm but I dont have enough data to support that definitively. Thought about maybe parsing down the statement for what the alerts is stating but that seems overkill.
=> Fix "Special Weather" Alert Type Not Found

src/integrations/env_canada.ts
There is currently a Smog Warning being issued by Environment Canada, which is not supported by the card.
This change adds support for this warning.
Here's the error I was getting before this change:
Here's what it looks like after this change:
This works for English, but I was unable to figure out how to test it for French (there doesn't seem to be a language setting for the Environment Canada integration?).
The title of the French warning on the website is "Avertissement de smog en vigueur pour" so I'm guessing the warning would be "Avertissement De Smog" and this set the French to just "Smog" too, but that's just a guess.
=> Add smog warning type for Environment Canada

src/integrations/env_canada.ts
=> Environment Canada (French): Fix Watch and Severe Thunderstorm events detection

src/integrations/dwd.ts
Fixes: #214
This PR fixes an issue with DWD integration that caused the `getEntityKind` function to fail when using translated `entity_id` and `friendly_name` to German. The function was expecting `sensor.dwd_weather_warnings_current_warning_level` and got `sensor.dwd_weather_warnings_aktuelle_warnstufe` since upstream integration was updated.
The solution here is to support both English and German translation keys. It covers 99% of use cases but it's not an ideal way to do this.
=> DWD: Fix entity type detection when using translated `enity_id`

README.md, src/data.ts, src/events-praser.ts, src/meteoalarm-card.ts, src/predefined-cards.ts, src/styles.ts, src/types.ts
Fixes: #207
This PR adds better support for customizing the card with [card-mod](https://github.com/thomasloven/lovelace-card-mod). Check [README](https://github.com/MrBartusek/MeteoalarmCard/tree/master#customizing-the-cards-appearance) for more information.
=> Improve custom CSS support

README.md
Apparently README was using the old way to specifying card-mod styles which have been removed now
https://github.com/thomasloven/lovelace-card-mod/releases/tag/v3.4.0
=> Update README card-mod example to car-mod 3.4.0

src/localize/languages/cs.json
Completed and improved Czech translation.
=> Update Czech translation

src/integrations/env_canada.ts
Fixes: #237
- Map `Avertissement D'` prefix to warning
- Map `Avis` and `Avis D'` to advisory
=> Improve coverage for french prefixes in env canada

README.md, src/styles.ts
Fixes: #231
This PR adds two new CSS variables
- `--headline-font-size`  for text size of header (alert name)
- `--caption-font-size` for caption
```yaml
type: custom:meteoalarm-card
entities:
- entity: sensor.32_weather_alert
integration: meteofrance
scaling_mode: disabled
card_mod:
style: |
ha-card {
--headline-font-size: 12px;
}
```
=> Expose headline and caption font size for card-mod

src/styles.ts
Fixes: #255
Since a couple of realises orange level warnings were shown as red warnings. This PR fixes that.
=> Fix orange warning level color
